Repository isontheline/vscode-sysmon, pull requests merged in 2024-08, with the labels that each got.

#11 chore: Update LICENSE file with additional copyright information
  LICENSE
Labels: documentation

#12 chore: Update LICENSE file with additional copyright information (#11)
  LICENSE
Labels: documentation

#17 WIP Auto Semver
  .github/workflows/build.yml
  .github/workflows/label_check.yml
  package.json
  renovate.json
Labels: patch

#18 WIP Auto Semver
  .github/workflows/build.yml
  build.gradle
Labels: patch

#19 WIP Auto Semver
  .github/workflows/build.yml
Labels: patch

#20 chore: Update .gitignore to include .gradle/ directory
  .gitignore
Labels: patch

#21 chore: Add GitHub Actions workflow to create releases
  .github/workflows/build.yml
  .github/workflows/create_release.yml
Labels: minor

#22 chore: Update GitHub Actions workflow to create releases
  .github/workflows/build.yml
  .github/workflows/create_release.yml
Labels: patch

#23 Update GitHub Actions workflow to create releases
  .github/workflows/build_deploy.yml
Labels: minor

#24 chore: Update GitHub Actions workflow to create releases
  .github/workflows/build_deploy.yml
Labels: minor

#26 Updating icons about network activity
  .github/workflows/label_check.yml
  package.json
Labels: enhancement, minor

#27 Updating icons about network activity
  .github/workflows/label_check.yml
  package.json
Labels: enhancement, minor

#28 chore: Update npm dependency to latest stable version
  .github/workflows/build_deploy.yml
  .github/workflows/label_check.yml
  package.json
Labels: dependency, patch

#32 chore: Update timeout minutes for label check workflow
  .github/workflows/label_check.yml
Labels: documentation, patch

#33 chore: Update timeout minutes for label check workflow
  .github/workflows/label_check.yml
Labels: documentation, patch
